// <auto-generated />
using System;
using HRBackend.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRBackend.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250409125919_UpdateUserSchemas")]
    partial class UpdateUserSchemas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HRBackend.Domain.Entities.Candidates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonalInfoId")
                        .HasColumnType("int");

                    b.Property<int>("StatusCandidataIdId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("WorkingGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_candidates");

                    b.HasIndex("Id");

                    b.HasIndex("PersonalInfoId");

                    b.HasIndex("StatusCandidataIdId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkScheduleId");

                    b.HasIndex("WorkingGroupId");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.Check", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCheck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_check")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_check");

                    b.HasIndex("UserId");

                    b.ToTable("check", (string)null);
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.DictStatusCandidata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_dict_status_candidata");

                    b.HasIndex("Id");

                    b.ToTable("dict_status_candidata", (string)null);
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_add")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PersonalInfoId")
                        .HasColumnType("int");

                    b.Property<int>("WorkScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_emploees");

                    b.HasIndex("Id");

                    b.HasIndex("PersonalInfoId");

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.PersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_add")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("email");

                    b.Property<string>("Middlename")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("middlename");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("name");

                    b.Property<string>("NameSocail")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("name_socail");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("phone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("surname");

                    b.Property<int>("TypeSocailId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_personal_info");

                    b.HasIndex("Id");

                    b.HasIndex("TypeSocailId");

                    b.ToTable("personal_info", (string)null);
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.TypeSocail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_type_socail");

                    b.HasIndex("Id");

                    b.ToTable("type_socail", (string)null);
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("login");

                    b.Property<string>("Middlename")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("middlename");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("surname");

                    b.Property<int>("WorkScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("WorkingGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Id");

                    b.HasIndex("WorkScheduleId");

                    b.HasIndex("WorkingGroupId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_work_shedule");

                    b.HasIndex("Id");

                    b.ToTable("work_shedule", (string)null);
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.WorkingGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_working_groups");

                    b.HasIndex("Id");

                    b.ToTable("working_groups", (string)null);
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.Candidates", b =>
                {
                    b.HasOne("HRBackend.Domain.Entities.PersonalInfo", "PersonalInfo")
                        .WithMany()
                        .HasForeignKey("PersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRBackend.Domain.Entities.DictStatusCandidata", "StatusCandidataId")
                        .WithMany()
                        .HasForeignKey("StatusCandidataIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRBackend.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRBackend.Domain.Entities.WorkSchedule", "WorkSchedule")
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRBackend.Domain.Entities.WorkingGroup", "WorkingGroup")
                        .WithMany()
                        .HasForeignKey("WorkingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalInfo");

                    b.Navigation("StatusCandidataId");

                    b.Navigation("User");

                    b.Navigation("WorkSchedule");

                    b.Navigation("WorkingGroup");
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.Check", b =>
                {
                    b.HasOne("HRBackend.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.Employees", b =>
                {
                    b.HasOne("HRBackend.Domain.Entities.PersonalInfo", "PersonalInfo")
                        .WithMany()
                        .HasForeignKey("PersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRBackend.Domain.Entities.WorkSchedule", "WorkSchedule")
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalInfo");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.PersonalInfo", b =>
                {
                    b.HasOne("HRBackend.Domain.Entities.TypeSocail", "TypeSocail")
                        .WithMany()
                        .HasForeignKey("TypeSocailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeSocail");
                });

            modelBuilder.Entity("HRBackend.Domain.Entities.Users", b =>
                {
                    b.HasOne("HRBackend.Domain.Entities.WorkSchedule", "WorkSchedule")
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRBackend.Domain.Entities.WorkingGroup", "WorkingGroup")
                        .WithMany()
                        .HasForeignKey("WorkingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkSchedule");

                    b.Navigation("WorkingGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
